Repository FISAFINAL/WooriOneBank, pull requests merged in 2024-04, with the labels that each got.

#18 feat: 기능 새롭게 개발(#13)
  src/main/java/com/fisa/woorionebank/account/entity/Account.java
  src/main/java/com/fisa/woorionebank/account/repository/AccountRepository.java
  src/main/java/com/fisa/woorionebank/account/repository/AccountRepositoryCustom.java
  src/main/java/com/fisa/woorionebank/account/repository/AccountRepositoryImpl.java
  src/main/java/com/fisa/woorionebank/common/dto/ResponseDTO.java
  src/main/java/com/fisa/woorionebank/common/execption/ErrorCode.java
  src/main/java/com/fisa/woorionebank/member/entity/Member.java
  src/main/java/com/fisa/woorionebank/member/repository/MemberRepository.java
  src/main/java/com/fisa/woorionebank/saving/controller/SavingController.java
  src/main/java/com/fisa/woorionebank/saving/domain/entity/Celebrity.java
  src/main/java/com/fisa/woorionebank/saving/domain/entity/DepositDay.java
  src/main/java/com/fisa/woorionebank/saving/domain/entity/Saving.java
  src/main/java/com/fisa/woorionebank/saving/domain/entity/SavingRule.java
  src/main/java/com/fisa/woorionebank/saving/domain/requestdto/SavingCreateRequestDTO.java
  src/main/java/com/fisa/woorionebank/saving/domain/responsedto/SavingDTO.java
  src/main/java/com/fisa/woorionebank/saving/domain/responsedto/SavingRuleDTO.java
  src/main/java/com/fisa/woorionebank/saving/repository/SavingRepository.java
  src/main/java/com/fisa/woorionebank/saving/repository/SavingRepositoryCustom.java
  src/main/java/com/fisa/woorionebank/saving/repository/SavingRepositoryImpl.java
  src/main/java/com/fisa/woorionebank/saving/service/SavingService.java
  src/main/java/com/fisa/woorionebank/savinghistory/entity/SavingHistory.java
  src/main/java/com/fisa/woorionebank/savinghistory/entity/TransactionType.java
Labels: :battery: Enhancement

#26 25 feat 최애적금규칙 생성 및 조회
  src/main/java/com/fisa/woorionebank/saving/controller/SavingController.java
  src/main/java/com/fisa/woorionebank/saving/domain/entity/SavingRule.java
  src/main/java/com/fisa/woorionebank/saving/domain/requestdto/SavingAddRuleRequestDTO.java
  src/main/java/com/fisa/woorionebank/saving/domain/requestdto/SavingCreateRequestDTO.java
  src/main/java/com/fisa/woorionebank/saving/domain/responsedto/RuleListDTO.java
  src/main/java/com/fisa/woorionebank/saving/domain/responsedto/SavingListDTO.java
  src/main/java/com/fisa/woorionebank/saving/domain/responsedto/SavingRuleDTO.java
  src/main/java/com/fisa/woorionebank/saving/repository/rule/SavingRuleRepository.java
  src/main/java/com/fisa/woorionebank/saving/repository/saving/SavingRepository.java
  src/main/java/com/fisa/woorionebank/saving/repository/saving/SavingRepositoryCustom.java
  src/main/java/com/fisa/woorionebank/saving/service/SavingService.java
  src/test/java/com/fisa/woorionebank/service/SavingServiceTest.java
Labels: :battery: Enhancement, :bear: BE, :cat: Bongsub, :sparkles: Feat

#28 [FEAT] 공연 응모 비즈니스 로직(#14)
  src/main/java/com/fisa/woorionebank/concert/controller/ConcertController.java
  src/main/java/com/fisa/woorionebank/concert/domain/entity/ConcertHistory.java
  src/main/java/com/fisa/woorionebank/concert/repository/jpa/ConcertHistoryRepository.java
  src/main/java/com/fisa/woorionebank/concert/service/ConcertService.java
  src/main/java/com/fisa/woorionebank/saving/repository/saving/SavingRepository.java
Labels: :battery: Enhancement, :bear: BE, :compass: API, :hammer: Refactoring, :heavy_check_mark: Test, :poodle: Yerin, :sparkles: Feat, :toolbox: Fix

#29 feat: 최애적금 조회 기능 구현(#27)
  src/main/java/com/fisa/woorionebank/account/service/AccountService.java
  src/main/java/com/fisa/woorionebank/member/entity/Member.java
  src/main/java/com/fisa/woorionebank/saving/controller/SavingController.java
  src/main/java/com/fisa/woorionebank/saving/domain/entity/Saving.java
  src/main/java/com/fisa/woorionebank/saving/service/SavingService.java
Labels: :battery: Enhancement, :bear: BE, :cat: Bongsub, :sparkles: Feat

#33 최애적금 입금내역 조회
  src/main/java/com/fisa/woorionebank/saving/controller/SavingController.java
  src/main/java/com/fisa/woorionebank/saving/domain/entity/SavingRule.java
  src/main/java/com/fisa/woorionebank/saving/domain/responsedto/SavingHistoryDTO.java
  src/main/java/com/fisa/woorionebank/saving/domain/responsedto/SavingHistoryListDTO.java
  src/main/java/com/fisa/woorionebank/saving/service/SavingService.java
  src/main/java/com/fisa/woorionebank/savinghistory/repository/SavingHistoryRepository.java
Labels: :battery: Enhancement, :bear: BE, :cat: Bongsub, :sparkles: Feat

#36 [FIX] 이미 선택된 좌석입니다(#35)
  src/main/java/com/fisa/woorionebank/concert/controller/ConcertController.java
  src/main/java/com/fisa/woorionebank/concert/repository/jpa/ConcertHistoryRepository.java
  src/main/java/com/fisa/woorionebank/concert/service/ConcertService.java
  src/main/java/com/fisa/woorionebank/seat/domain/dto/ResponseSeatDTO.java
Labels: :battery: Enhancement, :bear: BE, :hammer: Refactoring, :poodle: Yerin, :toolbox: Fix

#38 [FIX] Concert 테스트 코드(#37)
  src/main/java/com/fisa/woorionebank/concert/domain/dto/ConcertDTO.java
  src/main/java/com/fisa/woorionebank/concert/domain/entity/Concert.java
  src/main/java/com/fisa/woorionebank/concert/domain/entity/ConcertVenue.java
  src/main/java/com/fisa/woorionebank/concert/service/ConcertService.java
  src/test/java/com/fisa/woorionebank/service/ControllerServiceTest.java
Labels: :bear: BE, :heavy_check_mark: Test, :poodle: Yerin, :toolbox: Fix

#39 feat: 서비스분리 (#34)
  src/main/java/com/fisa/woorionebank/account/entity/Account.java
  src/main/java/com/fisa/woorionebank/saving/controller/SavingController.java
  src/main/java/com/fisa/woorionebank/saving/domain/entity/Saving.java
  src/main/java/com/fisa/woorionebank/saving/repository/saving/SavingRepository.java
  src/main/java/com/fisa/woorionebank/saving/repository/saving/SavingRepositoryCustom.java
  src/main/java/com/fisa/woorionebank/saving/repository/saving/SavingRepositoryImpl.java
  src/main/java/com/fisa/woorionebank/saving/service/SavingService.java
  src/main/java/com/fisa/woorionebank/saving/service/WeeklyDepositService.java
Labels: :battery: Enhancement, :bear: BE

#41 feat: 적금 자동이체 기능 구현(#40)
  src/main/java/com/fisa/woorionebank/saving/repository/saving/SavingRepositoryImpl.java
  src/main/java/com/fisa/woorionebank/saving/service/WeeklyDepositService.java
Labels: :battery: Enhancement, :bear: BE, :cat: Bongsub, :sparkles: Feat

#44 42 feat 적금상세조회
  src/main/java/com/fisa/woorionebank/common/execption/ErrorCode.java
  src/main/java/com/fisa/woorionebank/saving/controller/SavingController.java
  src/main/java/com/fisa/woorionebank/saving/domain/responsedto/SavingInfoDTO.java
  src/main/java/com/fisa/woorionebank/saving/service/SavingService.java
Labels: :battery: Enhancement, :bear: BE, :cat: Bongsub, :sparkles: Feat

#45 refactor: 공연 도메인 리팩토링(#43)
  src/main/java/com/fisa/woorionebank/common/execption/ErrorCode.java
  src/main/java/com/fisa/woorionebank/concert/controller/ConcertController.java
  src/main/java/com/fisa/woorionebank/concert/domain/dto/ConcertHistoryDTO.java
  src/main/java/com/fisa/woorionebank/concert/domain/dto/ResponseConcertDTO.java
  src/main/java/com/fisa/woorionebank/concert/domain/entity/Concert.java
  src/main/java/com/fisa/woorionebank/concert/domain/entity/ConcertHistory.java
  src/main/java/com/fisa/woorionebank/concert/domain/entity/ConcertVenue.java
  src/main/java/com/fisa/woorionebank/concert/repository/jpa/ConcertRepository.java
  src/main/java/com/fisa/woorionebank/concert/service/ConcertDrawService.java
  src/main/java/com/fisa/woorionebank/concert/service/ConcertService.java
  src/main/java/com/fisa/woorionebank/concert/util/ConcertUtils.java
  src/main/java/com/fisa/woorionebank/seat/repository/SeatRepository.java
  src/test/java/com/fisa/woorionebank/service/ControllerServiceTest.java
Labels: :battery: Enhancement, :bear: BE, :hammer: Refactoring

#50 46 refactor 최애적금 리팩토링
  src/main/java/com/fisa/woorionebank/account/entity/Account.java
  src/main/java/com/fisa/woorionebank/saving/controller/SavingController.java
  src/main/java/com/fisa/woorionebank/saving/service/SavingService.java
  src/main/java/com/fisa/woorionebank/saving/util/AccountNumberGenerator.java
  src/test/java/com/fisa/woorionebank/service/SavingServiceTest.java
Labels: :bear: BE, :cat: Bongsub, :toolbox: Fix

#55 test: 최애적금 로직 테스트
  src/main/java/com/fisa/woorionebank/saving/domain/responsedto/RuleListDTO.java
  src/main/java/com/fisa/woorionebank/saving/domain/responsedto/SavingHistoryListDTO.java
  src/main/java/com/fisa/woorionebank/saving/domain/responsedto/SavingInfoDTO.java
  src/main/java/com/fisa/woorionebank/saving/domain/responsedto/SavingListDTO.java
  src/main/java/com/fisa/woorionebank/saving/domain/responsedto/SavingRuleDTO.java
  src/main/java/com/fisa/woorionebank/saving/repository/rule/SavingRuleRepository.java
  src/main/java/com/fisa/woorionebank/saving/repository/rule/SavingRuleRepositoryCustom.java
  src/main/java/com/fisa/woorionebank/saving/repository/rule/SavingRuleRepositoryImpl.java
  src/main/java/com/fisa/woorionebank/saving/repository/saving/SavingRepositoryCustom.java
  src/main/java/com/fisa/woorionebank/saving/service/SavingService.java
  src/test/java/com/fisa/woorionebank/service/SavingServiceTest.java
Labels: :bear: BE, :cat: Bongsub, :heavy_check_mark: Test

#60 feat: 스웨거 설정추가
  src/main/java/com/fisa/woorionebank/common/execption/ErrorCode.java
  src/main/java/com/fisa/woorionebank/concert/controller/ConcertController.java
  src/main/java/com/fisa/woorionebank/member/controller/MemberController.java
  src/main/java/com/fisa/woorionebank/member/domain/dto/request/LoginDto.java
  src/main/java/com/fisa/woorionebank/member/domain/dto/request/RegisterDTO.java
  src/main/java/com/fisa/woorionebank/member/domain/dto/requestDto/LoginDto.java
  src/main/java/com/fisa/woorionebank/member/domain/dto/response/MemberDTO.java
  src/main/java/com/fisa/woorionebank/member/domain/dto/responseDto/ResponseDTO.java
  src/main/java/com/fisa/woorionebank/member/entity/Member.java
  src/main/java/com/fisa/woorionebank/member/service/MemberService.java
  src/main/java/com/fisa/woorionebank/saving/controller/SavingController.java
  src/main/java/com/fisa/woorionebank/saving/domain/requestdto/SavingCreateRequestDTO.java
  src/main/java/com/fisa/woorionebank/security/filter/JwtAuthenticationFilter.java
  src/test/java/com/fisa/woorionebank/service/MemberServiceTest.java
  src/test/java/com/fisa/woorionebank/service/SavingServiceTest.java
Labels: :bear: BE, :cat: Bongsub

#62 test
  src/main/java/com/fisa/woorionebank/member/controller/MemberController.java
  src/main/java/com/fisa/woorionebank/member/domain/dto/request/LoginDto.java
  src/main/java/com/fisa/woorionebank/member/repository/MemberRepository.java
  src/main/java/com/fisa/woorionebank/member/service/MemberService.java
  src/main/java/com/fisa/woorionebank/saving/controller/SavingController.java
  src/main/java/com/fisa/woorionebank/saving/service/SavingService.java
  src/main/java/com/fisa/woorionebank/security/service/JwtDetailsService.java
  src/test/java/com/fisa/woorionebank/dumy/Dummy.java
Labels: :battery: Enhancement, :bear: BE, :cat: Bongsub

#64 Dev에서 #61 브렌치로 반영
  README.md
  src/main/java/com/fisa/woorionebank/concert/domain/entity/Concert.java
  src/main/java/com/fisa/woorionebank/concert/domain/entity/ConcertVenue.java
  src/main/java/com/fisa/woorionebank/seat/entity/Seat.java
  src/test/java/com/fisa/woorionebank/dumy/Dummy.java
Labels: :bear: BE, :cat: Bongsub

#65 61 test jwt 테스트
  src/main/java/com/fisa/woorionebank/account/entity/Account.java
  src/main/java/com/fisa/woorionebank/card/entity/CardHistory.java
  src/main/java/com/fisa/woorionebank/concert/domain/entity/Concert.java
  src/main/java/com/fisa/woorionebank/concert/domain/entity/ConcertHistory.java
  src/main/java/com/fisa/woorionebank/concert/domain/entity/ConcertVenue.java
  src/main/java/com/fisa/woorionebank/interest/entity/InterestRate.java
  src/main/java/com/fisa/woorionebank/member/entity/Member.java
  src/main/java/com/fisa/woorionebank/saving/controller/SavingController.java
  src/main/java/com/fisa/woorionebank/saving/domain/entity/Celebrity.java
  src/main/java/com/fisa/woorionebank/saving/domain/entity/Saving.java
  src/main/java/com/fisa/woorionebank/saving/domain/entity/SavingRule.java
  src/main/java/com/fisa/woorionebank/saving/domain/responsedto/SavingDTO.java
  src/main/java/com/fisa/woorionebank/saving/service/SavingService.java
  src/main/java/com/fisa/woorionebank/savinghistory/entity/SavingHistory.java
  src/main/java/com/fisa/woorionebank/seat/entity/Seat.java
  src/main/java/com/fisa/woorionebank/security/filter/JwtAuthenticationFilter.java
  src/main/java/com/fisa/woorionebank/security/service/JwtDetailsService.java
  src/test/java/com/fisa/woorionebank/dumy/Dummy.java
Labels: :bear: BE, :cat: Bongsub

#70 69 feat 분산락 구현
  build.gradle
  src/main/java/com/fisa/woorionebank/concert/controller/ConcertController.java
  src/main/java/com/fisa/woorionebank/concert/repository/jpa/ConcertHistoryRepository.java
  src/main/java/com/fisa/woorionebank/concert/service/ConcertService.java
  src/main/java/com/fisa/woorionebank/config/redisson/AopForTransaction.java
  src/main/java/com/fisa/woorionebank/config/redisson/CustomSpringELParser.java
  src/main/java/com/fisa/woorionebank/config/redisson/DistributedLock.java
  src/main/java/com/fisa/woorionebank/config/redisson/DistributedLockAop.java
  src/main/java/com/fisa/woorionebank/config/redisson/RedissonConfig.java
  src/main/java/com/fisa/woorionebank/saving/controller/SavingController.java
  src/main/java/com/fisa/woorionebank/seat/repository/SeatRepository.java
  src/main/resources/logback-spring.xml
  src/test/java/com/fisa/woorionebank/dumy/Dummy.java
  src/test/java/com/fisa/woorionebank/service/ConcertServiceTest.java
  src/test/java/com/fisa/woorionebank/service/DistributedLockTest.java
Labels: :bear: BE, :cat: Bongsub, :sparkles: Feat
